# Generated by Django 6.0.4 on 2026-04-18 21:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hierarquia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='certificados/arquivos/')),
                ('foi_impresso_fisicamente', models.BooleanField(default=False, verbose_name='Certificados')),
                ('graduacao_alcancada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hierarquia.graduacao')),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
    ]
