# Generated by Django 6.0.4 on 2026-04-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='id',
            new_name='chave_autenticacao',
        ),
    ]
