# Generated by Django 6.0.4 on 2026-04-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0002_rename_id_certificado_chave_autenticacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='foi_impresso_fisicamente',
            field=models.BooleanField(default=False, verbose_name='Certificado impresso?'),
        ),
    ]
