# Generated by Django 6.0.4 on 2026-04-18 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Graduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(help_text='Quanto maior, mais graduado')),
                ('pode_ter_alunos', models.BooleanField(default=False)),
                ('valor_graduacao', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor para obter esta graduação', max_digits=10)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduacoes', to='hierarquia.modalidade')),
            ],
            options={
                'verbose_name_plural': 'Graduações',
                'ordering': ['-ordem'],
            },
        ),
    ]
