# Generated by Django 6.0.4 on 2026-04-19 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Evento')),
                ('data_evento', models.DateField(verbose_name='Data do Evento')),
                ('local', models.CharField(max_length=255, verbose_name='Local do Evento')),
                ('descricao', models.TextField(verbose_name='Descrição do Evento')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='eventos/banners/')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado?')),
                ('fechado', models.BooleanField(default=False, verbose_name='Fechado?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_evento'],
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('permite_comentarios', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=True)),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_postagem'],
            },
        ),
        migrations.CreateModel(
            name='FotoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='eventos/galeria/')),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='comunicacao.evento')),
            ],
        ),
    ]
